/**
 *
 *  ProjectInvitation.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "ProjectInvitation.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::project_calendar;

const std::string ProjectInvitation::Cols::_id = "\"id\"";
const std::string ProjectInvitation::Cols::_project_id = "\"project_id\"";
const std::string ProjectInvitation::Cols::_inviter_user_id = "\"inviter_user_id\"";
const std::string ProjectInvitation::Cols::_invitee_user_id = "\"invitee_user_id\"";
const std::string ProjectInvitation::Cols::_invitee_email = "\"invitee_email\"";
const std::string ProjectInvitation::Cols::_kind = "\"kind\"";
const std::string ProjectInvitation::Cols::_status = "\"status\"";
const std::string ProjectInvitation::Cols::_created_at = "\"created_at\"";
const std::string ProjectInvitation::Cols::_decided_at = "\"decided_at\"";
const std::string ProjectInvitation::Cols::_decided_by = "\"decided_by\"";
const std::string ProjectInvitation::primaryKeyName = "id";
const bool ProjectInvitation::hasPrimaryKey = true;
const std::string ProjectInvitation::tableName = "\"project_invitation\"";

const std::vector<typename ProjectInvitation::MetaData> ProjectInvitation::metaData_={
{"id","std::string","uuid",0,0,1,1},
{"project_id","std::string","uuid",0,0,0,1},
{"inviter_user_id","std::string","uuid",0,0,0,0},
{"invitee_user_id","std::string","uuid",0,0,0,0},
{"invitee_email","std::string","text",0,0,0,0},
{"kind","std::string","USER-DEFINED",0,0,0,1},
{"status","std::string","USER-DEFINED",0,0,0,1},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,1},
{"decided_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"decided_by","std::string","uuid",0,0,0,0}
};
const std::string &ProjectInvitation::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
ProjectInvitation::ProjectInvitation(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<std::string>(r["id"].as<std::string>());
        }
        if(!r["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(r["project_id"].as<std::string>());
        }
        if(!r["inviter_user_id"].isNull())
        {
            inviterUserId_=std::make_shared<std::string>(r["inviter_user_id"].as<std::string>());
        }
        if(!r["invitee_user_id"].isNull())
        {
            inviteeUserId_=std::make_shared<std::string>(r["invitee_user_id"].as<std::string>());
        }
        if(!r["invitee_email"].isNull())
        {
            inviteeEmail_=std::make_shared<std::string>(r["invitee_email"].as<std::string>());
        }
        if(!r["kind"].isNull())
        {
            kind_=std::make_shared<std::string>(r["kind"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["decided_at"].isNull())
        {
            auto timeStr = r["decided_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["decided_by"].isNull())
        {
            decidedBy_=std::make_shared<std::string>(r["decided_by"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            projectId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            inviterUserId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            inviteeUserId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            inviteeEmail_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            kind_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            decidedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

ProjectInvitation::ProjectInvitation(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            inviterUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            inviteeUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            inviteeEmail_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            kind_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            decidedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
}

ProjectInvitation::ProjectInvitation(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
    if(pJson.isMember("inviter_user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["inviter_user_id"].isNull())
        {
            inviterUserId_=std::make_shared<std::string>(pJson["inviter_user_id"].asString());
        }
    }
    if(pJson.isMember("invitee_user_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["invitee_user_id"].isNull())
        {
            inviteeUserId_=std::make_shared<std::string>(pJson["invitee_user_id"].asString());
        }
    }
    if(pJson.isMember("invitee_email"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["invitee_email"].isNull())
        {
            inviteeEmail_=std::make_shared<std::string>(pJson["invitee_email"].asString());
        }
    }
    if(pJson.isMember("kind"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["kind"].isNull())
        {
            kind_=std::make_shared<std::string>(pJson["kind"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("decided_at"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["decided_at"].isNull())
        {
            auto timeStr = pJson["decided_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("decided_by"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["decided_by"].isNull())
        {
            decidedBy_=std::make_shared<std::string>(pJson["decided_by"].asString());
        }
    }
}

void ProjectInvitation::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            inviterUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            inviteeUserId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            inviteeEmail_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            kind_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[8]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            decidedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
}

void ProjectInvitation::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<std::string>(pJson["id"].asString());
        }
    }
    if(pJson.isMember("project_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["project_id"].isNull())
        {
            projectId_=std::make_shared<std::string>(pJson["project_id"].asString());
        }
    }
    if(pJson.isMember("inviter_user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["inviter_user_id"].isNull())
        {
            inviterUserId_=std::make_shared<std::string>(pJson["inviter_user_id"].asString());
        }
    }
    if(pJson.isMember("invitee_user_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["invitee_user_id"].isNull())
        {
            inviteeUserId_=std::make_shared<std::string>(pJson["invitee_user_id"].asString());
        }
    }
    if(pJson.isMember("invitee_email"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["invitee_email"].isNull())
        {
            inviteeEmail_=std::make_shared<std::string>(pJson["invitee_email"].asString());
        }
    }
    if(pJson.isMember("kind"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["kind"].isNull())
        {
            kind_=std::make_shared<std::string>(pJson["kind"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("decided_at"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["decided_at"].isNull())
        {
            auto timeStr = pJson["decided_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("decided_by"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["decided_by"].isNull())
        {
            decidedBy_=std::make_shared<std::string>(pJson["decided_by"].asString());
        }
    }
}

const std::string &ProjectInvitation::getValueOfId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectInvitation::getId() const noexcept
{
    return id_;
}
void ProjectInvitation::setId(const std::string &pId) noexcept
{
    id_ = std::make_shared<std::string>(pId);
    dirtyFlag_[0] = true;
}
void ProjectInvitation::setId(std::string &&pId) noexcept
{
    id_ = std::make_shared<std::string>(std::move(pId));
    dirtyFlag_[0] = true;
}
const typename ProjectInvitation::PrimaryKeyType & ProjectInvitation::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &ProjectInvitation::getValueOfProjectId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(projectId_)
        return *projectId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectInvitation::getProjectId() const noexcept
{
    return projectId_;
}
void ProjectInvitation::setProjectId(const std::string &pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(pProjectId);
    dirtyFlag_[1] = true;
}
void ProjectInvitation::setProjectId(std::string &&pProjectId) noexcept
{
    projectId_ = std::make_shared<std::string>(std::move(pProjectId));
    dirtyFlag_[1] = true;
}

const std::string &ProjectInvitation::getValueOfInviterUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(inviterUserId_)
        return *inviterUserId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectInvitation::getInviterUserId() const noexcept
{
    return inviterUserId_;
}
void ProjectInvitation::setInviterUserId(const std::string &pInviterUserId) noexcept
{
    inviterUserId_ = std::make_shared<std::string>(pInviterUserId);
    dirtyFlag_[2] = true;
}
void ProjectInvitation::setInviterUserId(std::string &&pInviterUserId) noexcept
{
    inviterUserId_ = std::make_shared<std::string>(std::move(pInviterUserId));
    dirtyFlag_[2] = true;
}
void ProjectInvitation::setInviterUserIdToNull() noexcept
{
    inviterUserId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &ProjectInvitation::getValueOfInviteeUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(inviteeUserId_)
        return *inviteeUserId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectInvitation::getInviteeUserId() const noexcept
{
    return inviteeUserId_;
}
void ProjectInvitation::setInviteeUserId(const std::string &pInviteeUserId) noexcept
{
    inviteeUserId_ = std::make_shared<std::string>(pInviteeUserId);
    dirtyFlag_[3] = true;
}
void ProjectInvitation::setInviteeUserId(std::string &&pInviteeUserId) noexcept
{
    inviteeUserId_ = std::make_shared<std::string>(std::move(pInviteeUserId));
    dirtyFlag_[3] = true;
}
void ProjectInvitation::setInviteeUserIdToNull() noexcept
{
    inviteeUserId_.reset();
    dirtyFlag_[3] = true;
}

const std::string &ProjectInvitation::getValueOfInviteeEmail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(inviteeEmail_)
        return *inviteeEmail_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectInvitation::getInviteeEmail() const noexcept
{
    return inviteeEmail_;
}
void ProjectInvitation::setInviteeEmail(const std::string &pInviteeEmail) noexcept
{
    inviteeEmail_ = std::make_shared<std::string>(pInviteeEmail);
    dirtyFlag_[4] = true;
}
void ProjectInvitation::setInviteeEmail(std::string &&pInviteeEmail) noexcept
{
    inviteeEmail_ = std::make_shared<std::string>(std::move(pInviteeEmail));
    dirtyFlag_[4] = true;
}
void ProjectInvitation::setInviteeEmailToNull() noexcept
{
    inviteeEmail_.reset();
    dirtyFlag_[4] = true;
}

const std::string &ProjectInvitation::getValueOfKind() const noexcept
{
    static const std::string defaultValue = std::string();
    if(kind_)
        return *kind_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectInvitation::getKind() const noexcept
{
    return kind_;
}
void ProjectInvitation::setKind(const std::string &pKind) noexcept
{
    kind_ = std::make_shared<std::string>(pKind);
    dirtyFlag_[5] = true;
}
void ProjectInvitation::setKind(std::string &&pKind) noexcept
{
    kind_ = std::make_shared<std::string>(std::move(pKind));
    dirtyFlag_[5] = true;
}

const std::string &ProjectInvitation::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectInvitation::getStatus() const noexcept
{
    return status_;
}
void ProjectInvitation::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[6] = true;
}
void ProjectInvitation::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[6] = true;
}

const ::trantor::Date &ProjectInvitation::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProjectInvitation::getCreatedAt() const noexcept
{
    return createdAt_;
}
void ProjectInvitation::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[7] = true;
}

const ::trantor::Date &ProjectInvitation::getValueOfDecidedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(decidedAt_)
        return *decidedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &ProjectInvitation::getDecidedAt() const noexcept
{
    return decidedAt_;
}
void ProjectInvitation::setDecidedAt(const ::trantor::Date &pDecidedAt) noexcept
{
    decidedAt_ = std::make_shared<::trantor::Date>(pDecidedAt);
    dirtyFlag_[8] = true;
}
void ProjectInvitation::setDecidedAtToNull() noexcept
{
    decidedAt_.reset();
    dirtyFlag_[8] = true;
}

const std::string &ProjectInvitation::getValueOfDecidedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(decidedBy_)
        return *decidedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &ProjectInvitation::getDecidedBy() const noexcept
{
    return decidedBy_;
}
void ProjectInvitation::setDecidedBy(const std::string &pDecidedBy) noexcept
{
    decidedBy_ = std::make_shared<std::string>(pDecidedBy);
    dirtyFlag_[9] = true;
}
void ProjectInvitation::setDecidedBy(std::string &&pDecidedBy) noexcept
{
    decidedBy_ = std::make_shared<std::string>(std::move(pDecidedBy));
    dirtyFlag_[9] = true;
}
void ProjectInvitation::setDecidedByToNull() noexcept
{
    decidedBy_.reset();
    dirtyFlag_[9] = true;
}

void ProjectInvitation::updateId(const uint64_t id)
{
}

const std::vector<std::string> &ProjectInvitation::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "id",
        "project_id",
        "inviter_user_id",
        "invitee_user_id",
        "invitee_email",
        "kind",
        "status",
        "created_at",
        "decided_at",
        "decided_by"
    };
    return inCols;
}

void ProjectInvitation::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getInviterUserId())
        {
            binder << getValueOfInviterUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getInviteeUserId())
        {
            binder << getValueOfInviteeUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getInviteeEmail())
        {
            binder << getValueOfInviteeEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getKind())
        {
            binder << getValueOfKind();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDecidedAt())
        {
            binder << getValueOfDecidedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getDecidedBy())
        {
            binder << getValueOfDecidedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> ProjectInvitation::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void ProjectInvitation::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getId())
        {
            binder << getValueOfId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getProjectId())
        {
            binder << getValueOfProjectId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getInviterUserId())
        {
            binder << getValueOfInviterUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getInviteeUserId())
        {
            binder << getValueOfInviteeUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getInviteeEmail())
        {
            binder << getValueOfInviteeEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getKind())
        {
            binder << getValueOfKind();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getDecidedAt())
        {
            binder << getValueOfDecidedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getDecidedBy())
        {
            binder << getValueOfDecidedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value ProjectInvitation::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getInviterUserId())
    {
        ret["inviter_user_id"]=getValueOfInviterUserId();
    }
    else
    {
        ret["inviter_user_id"]=Json::Value();
    }
    if(getInviteeUserId())
    {
        ret["invitee_user_id"]=getValueOfInviteeUserId();
    }
    else
    {
        ret["invitee_user_id"]=Json::Value();
    }
    if(getInviteeEmail())
    {
        ret["invitee_email"]=getValueOfInviteeEmail();
    }
    else
    {
        ret["invitee_email"]=Json::Value();
    }
    if(getKind())
    {
        ret["kind"]=getValueOfKind();
    }
    else
    {
        ret["kind"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getDecidedAt())
    {
        ret["decided_at"]=getDecidedAt()->toDbStringLocal();
    }
    else
    {
        ret["decided_at"]=Json::Value();
    }
    if(getDecidedBy())
    {
        ret["decided_by"]=getValueOfDecidedBy();
    }
    else
    {
        ret["decided_by"]=Json::Value();
    }
    return ret;
}

std::string ProjectInvitation::toString() const
{
    return toJson().toStyledString();
}

Json::Value ProjectInvitation::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getProjectId())
            {
                ret[pMasqueradingVector[1]]=getValueOfProjectId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getInviterUserId())
            {
                ret[pMasqueradingVector[2]]=getValueOfInviterUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getInviteeUserId())
            {
                ret[pMasqueradingVector[3]]=getValueOfInviteeUserId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getInviteeEmail())
            {
                ret[pMasqueradingVector[4]]=getValueOfInviteeEmail();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getKind())
            {
                ret[pMasqueradingVector[5]]=getValueOfKind();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[6]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[7]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getDecidedAt())
            {
                ret[pMasqueradingVector[8]]=getDecidedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getDecidedBy())
            {
                ret[pMasqueradingVector[9]]=getValueOfDecidedBy();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getProjectId())
    {
        ret["project_id"]=getValueOfProjectId();
    }
    else
    {
        ret["project_id"]=Json::Value();
    }
    if(getInviterUserId())
    {
        ret["inviter_user_id"]=getValueOfInviterUserId();
    }
    else
    {
        ret["inviter_user_id"]=Json::Value();
    }
    if(getInviteeUserId())
    {
        ret["invitee_user_id"]=getValueOfInviteeUserId();
    }
    else
    {
        ret["invitee_user_id"]=Json::Value();
    }
    if(getInviteeEmail())
    {
        ret["invitee_email"]=getValueOfInviteeEmail();
    }
    else
    {
        ret["invitee_email"]=Json::Value();
    }
    if(getKind())
    {
        ret["kind"]=getValueOfKind();
    }
    else
    {
        ret["kind"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getDecidedAt())
    {
        ret["decided_at"]=getDecidedAt()->toDbStringLocal();
    }
    else
    {
        ret["decided_at"]=Json::Value();
    }
    if(getDecidedBy())
    {
        ret["decided_by"]=getValueOfDecidedBy();
    }
    else
    {
        ret["decided_by"]=Json::Value();
    }
    return ret;
}

bool ProjectInvitation::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(1, "project_id", pJson["project_id"], err, true))
            return false;
    }
    else
    {
        err="The project_id column cannot be null";
        return false;
    }
    if(pJson.isMember("inviter_user_id"))
    {
        if(!validJsonOfField(2, "inviter_user_id", pJson["inviter_user_id"], err, true))
            return false;
    }
    if(pJson.isMember("invitee_user_id"))
    {
        if(!validJsonOfField(3, "invitee_user_id", pJson["invitee_user_id"], err, true))
            return false;
    }
    if(pJson.isMember("invitee_email"))
    {
        if(!validJsonOfField(4, "invitee_email", pJson["invitee_email"], err, true))
            return false;
    }
    if(pJson.isMember("kind"))
    {
        if(!validJsonOfField(5, "kind", pJson["kind"], err, true))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(6, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("decided_at"))
    {
        if(!validJsonOfField(8, "decided_at", pJson["decided_at"], err, true))
            return false;
    }
    if(pJson.isMember("decided_by"))
    {
        if(!validJsonOfField(9, "decided_by", pJson["decided_by"], err, true))
            return false;
    }
    return true;
}
bool ProjectInvitation::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProjectInvitation::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("project_id"))
    {
        if(!validJsonOfField(1, "project_id", pJson["project_id"], err, false))
            return false;
    }
    if(pJson.isMember("inviter_user_id"))
    {
        if(!validJsonOfField(2, "inviter_user_id", pJson["inviter_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("invitee_user_id"))
    {
        if(!validJsonOfField(3, "invitee_user_id", pJson["invitee_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("invitee_email"))
    {
        if(!validJsonOfField(4, "invitee_email", pJson["invitee_email"], err, false))
            return false;
    }
    if(pJson.isMember("kind"))
    {
        if(!validJsonOfField(5, "kind", pJson["kind"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(6, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(7, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("decided_at"))
    {
        if(!validJsonOfField(8, "decided_at", pJson["decided_at"], err, false))
            return false;
    }
    if(pJson.isMember("decided_by"))
    {
        if(!validJsonOfField(9, "decided_by", pJson["decided_by"], err, false))
            return false;
    }
    return true;
}
bool ProjectInvitation::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool ProjectInvitation::validJsonOfField(size_t index,
                                         const std::string &fieldName,
                                         const Json::Value &pJson,
                                         std::string &err,
                                         bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
