/**
 *
 *  TeamTaskAssignment.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "TeamTaskAssignment.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::project_calendar;

const std::string TeamTaskAssignment::Cols::_team_id = "\"team_id\"";
const std::string TeamTaskAssignment::Cols::_task_id = "\"task_id\"";
const std::string TeamTaskAssignment::Cols::_assigned_at = "\"assigned_at\"";
const std::vector<std::string> TeamTaskAssignment::primaryKeyName = {"team_id","task_id"};
const bool TeamTaskAssignment::hasPrimaryKey = true;
const std::string TeamTaskAssignment::tableName = "\"team_task_assignment\"";

const std::vector<typename TeamTaskAssignment::MetaData> TeamTaskAssignment::metaData_={
{"team_id","std::string","uuid",0,0,1,1},
{"task_id","std::string","uuid",0,0,1,1},
{"assigned_at","::trantor::Date","timestamp with time zone",0,0,0,1}
};
const std::string &TeamTaskAssignment::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
TeamTaskAssignment::TeamTaskAssignment(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["team_id"].isNull())
        {
            teamId_=std::make_shared<std::string>(r["team_id"].as<std::string>());
        }
        if(!r["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(r["task_id"].as<std::string>());
        }
        if(!r["assigned_at"].isNull())
        {
            auto timeStr = r["assigned_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                assignedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            teamId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            taskId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                assignedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

TeamTaskAssignment::TeamTaskAssignment(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            teamId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                assignedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

TeamTaskAssignment::TeamTaskAssignment(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("team_id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["team_id"].isNull())
        {
            teamId_=std::make_shared<std::string>(pJson["team_id"].asString());
        }
    }
    if(pJson.isMember("task_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson["task_id"].asString());
        }
    }
    if(pJson.isMember("assigned_at"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["assigned_at"].isNull())
        {
            auto timeStr = pJson["assigned_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                assignedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void TeamTaskAssignment::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            teamId_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[2]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                assignedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void TeamTaskAssignment::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("team_id"))
    {
        if(!pJson["team_id"].isNull())
        {
            teamId_=std::make_shared<std::string>(pJson["team_id"].asString());
        }
    }
    if(pJson.isMember("task_id"))
    {
        if(!pJson["task_id"].isNull())
        {
            taskId_=std::make_shared<std::string>(pJson["task_id"].asString());
        }
    }
    if(pJson.isMember("assigned_at"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["assigned_at"].isNull())
        {
            auto timeStr = pJson["assigned_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                assignedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &TeamTaskAssignment::getValueOfTeamId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(teamId_)
        return *teamId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TeamTaskAssignment::getTeamId() const noexcept
{
    return teamId_;
}
void TeamTaskAssignment::setTeamId(const std::string &pTeamId) noexcept
{
    teamId_ = std::make_shared<std::string>(pTeamId);
    dirtyFlag_[0] = true;
}
void TeamTaskAssignment::setTeamId(std::string &&pTeamId) noexcept
{
    teamId_ = std::make_shared<std::string>(std::move(pTeamId));
    dirtyFlag_[0] = true;
}

const std::string &TeamTaskAssignment::getValueOfTaskId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(taskId_)
        return *taskId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &TeamTaskAssignment::getTaskId() const noexcept
{
    return taskId_;
}
void TeamTaskAssignment::setTaskId(const std::string &pTaskId) noexcept
{
    taskId_ = std::make_shared<std::string>(pTaskId);
    dirtyFlag_[1] = true;
}
void TeamTaskAssignment::setTaskId(std::string &&pTaskId) noexcept
{
    taskId_ = std::make_shared<std::string>(std::move(pTaskId));
    dirtyFlag_[1] = true;
}

const ::trantor::Date &TeamTaskAssignment::getValueOfAssignedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(assignedAt_)
        return *assignedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &TeamTaskAssignment::getAssignedAt() const noexcept
{
    return assignedAt_;
}
void TeamTaskAssignment::setAssignedAt(const ::trantor::Date &pAssignedAt) noexcept
{
    assignedAt_ = std::make_shared<::trantor::Date>(pAssignedAt);
    dirtyFlag_[2] = true;
}

void TeamTaskAssignment::updateId(const uint64_t id)
{
}
typename TeamTaskAssignment::PrimaryKeyType TeamTaskAssignment::getPrimaryKey() const
{
    return std::make_tuple(*teamId_,*taskId_);
}

const std::vector<std::string> &TeamTaskAssignment::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "team_id",
        "task_id",
        "assigned_at"
    };
    return inCols;
}

void TeamTaskAssignment::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTeamId())
        {
            binder << getValueOfTeamId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTaskId())
        {
            binder << getValueOfTaskId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAssignedAt())
        {
            binder << getValueOfAssignedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> TeamTaskAssignment::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void TeamTaskAssignment::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getTeamId())
        {
            binder << getValueOfTeamId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getTaskId())
        {
            binder << getValueOfTaskId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getAssignedAt())
        {
            binder << getValueOfAssignedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value TeamTaskAssignment::toJson() const
{
    Json::Value ret;
    if(getTeamId())
    {
        ret["team_id"]=getValueOfTeamId();
    }
    else
    {
        ret["team_id"]=Json::Value();
    }
    if(getTaskId())
    {
        ret["task_id"]=getValueOfTaskId();
    }
    else
    {
        ret["task_id"]=Json::Value();
    }
    if(getAssignedAt())
    {
        ret["assigned_at"]=getAssignedAt()->toDbStringLocal();
    }
    else
    {
        ret["assigned_at"]=Json::Value();
    }
    return ret;
}

std::string TeamTaskAssignment::toString() const
{
    return toJson().toStyledString();
}

Json::Value TeamTaskAssignment::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getTeamId())
            {
                ret[pMasqueradingVector[0]]=getValueOfTeamId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTaskId())
            {
                ret[pMasqueradingVector[1]]=getValueOfTaskId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getAssignedAt())
            {
                ret[pMasqueradingVector[2]]=getAssignedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getTeamId())
    {
        ret["team_id"]=getValueOfTeamId();
    }
    else
    {
        ret["team_id"]=Json::Value();
    }
    if(getTaskId())
    {
        ret["task_id"]=getValueOfTaskId();
    }
    else
    {
        ret["task_id"]=Json::Value();
    }
    if(getAssignedAt())
    {
        ret["assigned_at"]=getAssignedAt()->toDbStringLocal();
    }
    else
    {
        ret["assigned_at"]=Json::Value();
    }
    return ret;
}

bool TeamTaskAssignment::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("team_id"))
    {
        if(!validJsonOfField(0, "team_id", pJson["team_id"], err, true))
            return false;
    }
    else
    {
        err="The team_id column cannot be null";
        return false;
    }
    if(pJson.isMember("task_id"))
    {
        if(!validJsonOfField(1, "task_id", pJson["task_id"], err, true))
            return false;
    }
    else
    {
        err="The task_id column cannot be null";
        return false;
    }
    if(pJson.isMember("assigned_at"))
    {
        if(!validJsonOfField(2, "assigned_at", pJson["assigned_at"], err, true))
            return false;
    }
    return true;
}
bool TeamTaskAssignment::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TeamTaskAssignment::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("team_id"))
    {
        if(!validJsonOfField(0, "team_id", pJson["team_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("task_id"))
    {
        if(!validJsonOfField(1, "task_id", pJson["task_id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("assigned_at"))
    {
        if(!validJsonOfField(2, "assigned_at", pJson["assigned_at"], err, false))
            return false;
    }
    return true;
}
bool TeamTaskAssignment::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool TeamTaskAssignment::validJsonOfField(size_t index,
                                          const std::string &fieldName,
                                          const Json::Value &pJson,
                                          std::string &err,
                                          bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
